name: PR Quality Gate

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2
      - name: Analyze
        uses: github/codeql-action/analyze@v2

  coderabbit-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write   # PR에 코멘트 달 수 있는 권한만 허용
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Run CodeRabbit
        uses: coderabbitai/ai-pr-reviewer@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
